name: ruby-2
on: push
env:
  PROXY: proxy.zyte.com:8010
  URL: https://httpbin.scrapinghub.com/ip
  KEY: ${{secrets.KEY}}
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ruby-2
        run: make ruby-2
